### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by grasshaussoftware** [official-antique/InstaPy2#4]
Traceback (most recent call last):
  File "script.py", line 2, in <module>
    from instapy2 import InstaPy2
  File "/home/deusopus/InstaPy2/instapy2/__init__.py", line 4, in <module>
    from .instapy2 import InstaPy2
  File "/home/deusopus/InstaPy2/instapy2/instapy2.py", line 1, in <module>
    from .instapy2_base import InstaPy2Base
  File "/home/deusopus/InstaPy2/instapy2/instapy2_base.py", line 3, in <module>
    from .comment_util import CommentUtil
  File "/home/deusopus/InstaPy2/instapy2/comment_util.py", line 7, in <module>
    class CommentUtil:
  File "/home/deusopus/InstaPy2/instapy2/comment_util.py", line 16, in CommentUtil
    def get_comment_from_comments(self, comments: list[str] = []) -> str:
TypeError: 'type' object is not subscriptable

**Comment by official-antique** [comment]
Fixed by using typing.List instead of the built-in list in an earlier commit.
